### ISSUE TITLE
Tiny example doc still has a step to deploy the proxy

### ISSUE THREAD

**Issue by MikeSpreitzer** [containercafe/containercafe#146]
https://github.com/containercafe/containercafe/blob/master/examples/tiny-example.md#optionally-deploy-the-openradiant-api-proxy says "Now you have an option to deploy and use the API proxy".
CC @linsun 
CC @akanso

**Comment by akanso** [comment]
Should we add the option of deploying the Proxy in ansible?

**Comment by MikeSpreitzer** [comment]
Currently the ansible deploys the proxy unconditionally.  I have not heard someone tell me a reason to make it conditional.

**Comment by MikeSpreitzer** [comment]
Closing this issue because I think the doc has been updated to reflect the current truth of this matter.
