### ISSUE TITLE
tidy up the run docker.sh

### ISSUE THREAD

**Issue by akanso** [containercafe/containercafe#4]
This image name used should be parametrized:
image: containercafe/api-proxy  -> image: {{api-proxy_image}} 

The env variable name should be capitalized, the proxy code should be able to read the capitalized version:
-e "env_name=$env_name" -> -e “ENV_NAME=$env_name"

**Comment by mrsabath** [comment]
Updated the proxy to handle upper case env. variables. The rundocker.sh script allows selecting the image to run for proxy
