### ISSUE TITLE
Issue unarchiving Flannel

### ISSUE THREAD

**Issue by jsloyer** [containercafe/containercafe#92]
When running the following ansible task I get the following error.
```
( cd ansible; \
  ansible-playbook -v -i ../examples/envs/dev-vbox/radiant01.hosts shard.yml \
      -e "envs=../examples/envs cluster_name=dev-vbox-radiant01 network_kind=flannel" )
```

```
TASK [flannel-local-prep : fetch Flannel archive] ******************************
Tuesday 06 September 2016  16:06:09 -0400 (0:00:00.200)       0:00:07.894 *****
ok: [localhost] => {"changed": false, "checksum_dest": "fab60fdf23b029fa39badc008fe951bce5046caa", "checksum_src": "fab60fdf23b029fa39badc008fe951bce5046caa", "dest": "/Users/jsloyer/tmp/flannel-0.5.5-linux-amd64.tar.gz", "gid": 20, "group": "staff", "md5sum": "972c717254775bef528f040af804f2cc", "mode": "0644", "msg": "OK (3489977 bytes)", "owner": "jsloyer", "size": 3489977, "src": "/var/folders/q9/vn87rwnx36s02mb_k8py7pfr0000gn/T/tmpQ0axKS", "state": "file", "uid": 501, "url": "https://github.com/coreos/flannel/releases/download/v0.5.5/flannel-0.5.5-linux-amd64.tar.gz"}

TASK [flannel-local-prep : unarchive Flannel] **********************************
Tuesday 06 September 2016  16:06:15 -0400 (0:00:06.243)       0:00:14.137 *****
fatal: [localhost]: FAILED! => {"changed": false, "dest": "/Users/jsloyer/tmp/", "failed": true, "gid": 20, "group": "staff", "handler": "TgzArchive", "mode": "0755", "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/Users/jsloyer/tmp/flannel-0.5.5/flanneld'", "owner": "jsloyer", "size": 340, "src": "/Users/jsloyer/.ansible/tmp/ansible-tmp-1473192375.98-42071909129875/source", "stat": {"exists": false}, "state": "directory", "uid": 501}
```

The task is expecting the folder `/Users/jsloyer/tmp/flannel-0.5.5` to exist and it doesn't.

**Comment by jsloyer** [comment]
It looks like there is a bug with flannel and unarchiving `.tar.gz` files that have a directory embedded in them.

**Comment by MikeSpreitzer** [comment]
Hmm, I don't know why you would have this problem and all the other trials before this not have the same problem.

**Comment by jsloyer** [comment]
@jessexu is having this issue as well

**Comment by jsloyer** [comment]
I am using ansible 2.1.1.0

**Comment by MikeSpreitzer** [comment]
I tried the tiny example again, starting from scratch, and did not have this problem.  Attached is the typescript.  You can see that I am also using Ansible 2.1.1.0, and started with no `~/tmp` and no `~/.openradiant`.

[TinyExampleSuccess.txt](https://github.com/containercafe/containercafe/files/458244/TinyExampleSuccess.txt)

**Comment by MikeSpreitzer** [comment]
My installer machine is running MacOS 10.10.5.  What is yours running?

**Comment by jsloyer** [comment]
I am on OSX `10.11.6`.  I wiped everything out and still got the same error.  Attaching the output below.
[error.txt](https://github.com/containercafe/containercafe/files/459081/error.txt)

**Comment by MikeSpreitzer** [comment]
Thanks.  Could you please also share a zip of your `~/tmp`, as seen after the playbook crashes?

**Comment by jsloyer** [comment]
@MikeSpreitzer attached the output of `~/tmp/`
[tmp.zip](https://github.com/containercafe/containercafe/files/459158/tmp.zip)

**Comment by jessexu20** [comment]
After checking the success script, the diff I found that is that for mac user, you have to install gtar through `brew install gnu-tar`

**Comment by jsloyer** [comment]
@MikeSpreitzer should we add a check to the ansible script, doc it, or what?

**Comment by MikeSpreitzer** [comment]
Here is my `~/tmp` after successful completion of the shard playbook:
[tmp.zip](https://github.com/containercafe/containercafe/files/459595/tmp.zip)

**Comment by MikeSpreitzer** [comment]
@jsloyer @jessexu20 what do you get from `tar --version` on your installer machine if it has this problem?  Have you tested gnu-tar?  What does it report from `tar --version`?

Here is what I see:
```
mjs10:~ mspreitz$ tar --version
bsdtar 2.8.3 - libarchive 2.8.3
```

**Comment by jessexu20** [comment]
```
jesses-mbp:ansible jesse$ tar --version
bsdtar 2.8.3 - libarchive 2.8.3
```

**Comment by MikeSpreitzer** [comment]
@jessexu20 is that when the problem happens or when it does not happen?

**Comment by jessexu20** [comment]
after you install `gun-tar`, there is no problem

**Comment by MikeSpreitzer** [comment]
Can I please see the output of `tar --version` *before* someone installs gnu-tar?

**Comment by jessexu20** [comment]
it is the same

```
yuns-mbp:~ yun$ tar --version
bsdtar 2.8.3 - libarchive 2.8.3```

**Comment by MikeSpreitzer** [comment]
So this means installing gnu-tar is not the critical step.

**Comment by MikeSpreitzer** [comment]
So I tried `brew uninstall gnu-tar`, and that finished without complaint.  But `tar --version` still produces the same output.  But the symptom reported in this issue appears!

**Comment by MikeSpreitzer** [comment]
This is very weird.  For now I prefer to document the gnu-tar workaround; I will make a PR to do that.  I will leave this issue open until the problem is properly diagnosed.  I wonder if it is https://github.com/ansible/ansible-modules-core/issues/3631

**Comment by MikeSpreitzer** [comment]
Just to emphasize the weirdness:
```
mjs10:containercafe mspreitz$ brew install gnu-tar
==> Downloading https://homebrew.bintray.com/bottles/gnu-tar-1.29.yosemite.bottl
######################################################################## 100.0%
==> Pouring gnu-tar-1.29.yosemite.bottle.tar.gz
==> Caveats
gnu-tar has been installed as "gtar".

If you really need to use it as "tar", you can add a "gnubin" directory
to your PATH from your bashrc like:

    PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"

Additionally, you can access their man pages with normal names if you add
the "gnuman" directory to your MANPATH from your bashrc as well:

    MANPATH="/usr/local/opt/gnu-tar/libexec/gnuman:$MANPATH"

==> Summary
🍺  /usr/local/Cellar/gnu-tar/1.29: 14 files, 1.7M
```

**Comment by MikeSpreitzer** [comment]
Yes, the root cause is a bug, ansible-modules-core issue 3631.  It affects both `.zip` files and `.tar.gz` files (perhaps unsurprisingly).

**Comment by MikeSpreitzer** [comment]
The unarchive module bug is _absent_ (i.e., the unarchive module works as documented) in Ansible 1.9.5 and 1.9.6.

**Comment by MikeSpreitzer** [comment]
I rediscovered https://docs.ansible.com/ansible/unarchive_module.html#notes --- which says that `gtar` is required on the managed nodes.  So this issue is not about an Ansible bug but rather the fact that the user did not realize the need for `gtar`.

**Comment by MikeSpreitzer** [comment]
I have updated the doc on creating an installer machine to explain that gtar is needed.
