### ISSUE TITLE
Lack of gofmt enforcement for proxy

### ISSUE THREAD

**Issue by MikeSpreitzer** [containercafe/containercafe#93]
We should enforce gofmt discipline.
Perhaps with a pre-commit hook, like the one mentioned in https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md#committing-changes-to-your-fork

Witness https://github.com/containercafe/containercafe/pull/90

**Comment by MikeSpreitzer** [comment]
and witness #95

**Comment by MikeSpreitzer** [comment]
My point here is not to fix the current formatting problems but rather to establish a process that prevents formatting problems from being merged.

**Comment by mrsabath** [comment]
This is being addressed by #159
