### ISSUE TITLE
confusion that generated PR 96

### ISSUE THREAD

**Issue by MikeSpreitzer** [containercafe/containercafe#97]
Is there a documentation problem that caused #96 to be opened?
CC @jsloyer

**Comment by jsloyer** [comment]
no documentation issue, the code gets reformatted in any decent go ide, vscode or atom.  It might be good to enforce this with travis on PR submission.

**Comment by MikeSpreitzer** [comment]
@jsloyer did you comment on the wrong issue?

**Comment by MikeSpreitzer** [comment]
Sorry, I started with the wrong reference.

**Comment by mrsabath** [comment]
Added proper description in Proxy Readme.
